function legend2()

xlabel('version (4 = dsyev)');
ylabel('temps (en secondes)');
lg = legend('imat = 1', ...
    'imat = 2', ...
    'imat = 3', ...
    'imat = 4', ...
    'Location','Best');
set(lg,'Interpreter','Latex');
end

